name: build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout the source code
      uses: actions/checkout@v2
    - name: build (debug)
      run: cargo build --verbose
    - name: run tests
      run: cargo test --verbose
